// @vitest-environment node
import { afterEach, describe, expect, it } from 'vitest';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..', '..');
const installer = join(repoRoot, 'install.sh');

/** No first-registrant admin: on a public instance that is whoever finds sign-up first. */

const SAMPLE_ENV = [
  '# Railhook — generated by install.sh',
  'WEBHOOK_ENCRYPTION_KEY=kQ2v9ZpL7xR4mN8sT1wY6bC3dF0gH5jK9nM2pQ7rS4t',
  'APP_BASE_URL=https://hooks.example.com',
  '',
].join('\n');

const dirs: string[] = [];

function installation(env = SAMPLE_ENV) {
  const dir = mkdtempSync(join(tmpdir(), 'railhook-admin-email-'));
  dirs.push(dir);
  writeFileSync(join(dir, '.env'), env, { mode: 0o600 });
  return dir;
}

function run(...args: string[]) {
  return spawnSync('bash', [installer, ...args], {
    encoding: 'utf8',
    env: { PATH: process.env.PATH ?? '/usr/bin:/bin', HOME: tmpdir(), NO_COLOR: '1' },
  });
}

afterEach(() => {
  while (dirs.length) rmSync(dirs.pop()!, { recursive: true, force: true });
});

describe('install.sh --admin-email', () => {
  it('is documented in --help', () => {
    const help = run('--help');
    expect(help.status).toBe(0);
    expect(help.stdout).toMatch(/--admin-email <address>/);
  });

  it('names the platform admins of an existing installation on --refresh', () => {
    const dir = installation();
    const result = run('--refresh', '--dir', dir, '--admin-email', 'ops@example.com,oncall@example.com');
    expect(result.status, result.stderr).toBe(0);

    const env = readFileSync(join(dir, '.env'), 'utf8');
    expect(env).toMatch(/^PLATFORM_ADMIN_EMAILS=ops@example.com,oncall@example.com$/m);
    expect(env, 'every other line is left alone').toContain('APP_BASE_URL=https://hooks.example.com');
    expect(statSync(join(dir, '.env')).mode & 0o777).toBe(0o600);
  });

  it('replaces the list rather than adding a second line', () => {
    const dir = installation(`${SAMPLE_ENV}PLATFORM_ADMIN_EMAILS=old@example.com\n`);
    expect(run('--refresh', '--dir', dir, '--admin-email', 'new@example.com').status).toBe(0);

    const lines = readFileSync(join(dir, '.env'), 'utf8').split('\n').filter((l) => l.startsWith('PLATFORM_ADMIN_EMAILS='));
    expect(lines).toEqual(['PLATFORM_ADMIN_EMAILS=new@example.com']);
  });

  it('refuses something that is not an email address, and changes nothing', () => {
    const dir = installation();
    for (const bad of ['not-an-email', 'ops@', 'ops@example.com,', 'a b@example.com', 'ops@example.com;rm -rf /']) {
      const result = run('--refresh', '--dir', dir, '--admin-email', bad);
      expect(result.status, bad).not.toBe(0);
      expect(result.stderr).toMatch(/--admin-email/);
    }
    expect(readFileSync(join(dir, '.env'), 'utf8')).toBe(SAMPLE_ENV);
  });

  it('leaves the list alone when the flag is not given', () => {
    const dir = installation(`${SAMPLE_ENV}PLATFORM_ADMIN_EMAILS=ops@example.com\n`);
    expect(run('--refresh', '--dir', dir).status).toBe(0);
    expect(readFileSync(join(dir, '.env'), 'utf8')).toMatch(/^PLATFORM_ADMIN_EMAILS=ops@example.com$/m);
  });
});
