// @vitest-environment node
import { afterEach, describe, expect, it } from 'vitest';
import { spawnSync } from 'node:child_process';
import { chmodSync, mkdtempSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..', '..');
const read = (p: string) => readFileSync(join(repoRoot, p), 'utf8');

function helperSource(): string {
  const installer = read('install.sh');
  const start = installer.indexOf(`<<'HELPER'\n`);
  const end = installer.indexOf('\nHELPER\n', start);
  expect(start, 'the helper heredoc in install.sh').toBeGreaterThan(-1);
  expect(end).toBeGreaterThan(start);
  return installer.slice(start + `<<'HELPER'\n`.length, end + 1);
}

const SAMPLE_ENV = [
  '# Railhook — generated by install.sh',
  'WEBHOOK_ENCRYPTION_KEY=kQ2v9ZpL7xR4mN8sT1wY6bC3dF0gH5jK9nM2pQ7rS4t',
  'API_IMAGE_TAG=2.17.1',
  '',
  '# Mail',
  'EMAIL_ENABLED=false',
  'SMTP_HOST=localhost',
  'BILLING_ENABLED=false',
  '',
].join('\n');

const dirs: string[] = [];

function install() {
  const dir = mkdtempSync(join(tmpdir(), 'railhook-settings-'));
  dirs.push(dir);
  const bin = join(dir, 'bin');
  spawnSync('mkdir', ['-p', bin]);
  // Only `docker compose version` must succeed; nothing else may be called.
  writeFileSync(join(bin, 'docker'), '#!/bin/sh\necho "docker $*" >> "$(dirname "$0")/calls"\nexit 0\n');
  chmodSync(join(bin, 'docker'), 0o755);
  writeFileSync(join(dir, 'railhook'), helperSource());
  chmodSync(join(dir, 'railhook'), 0o755);
  writeFileSync(join(dir, '.env'), SAMPLE_ENV);
  chmodSync(join(dir, '.env'), 0o600);
  return { dir, bin, env: join(dir, '.env') };
}

function run(dir: string, bin: string, args: string[], input: string, extraEnv: Record<string, string> = {}) {
  const result = spawnSync('bash', [join(dir, 'railhook'), ...args], {
    input,
    encoding: 'utf8',
    env: { PATH: `${bin}:${process.env.PATH ?? '/usr/bin:/bin'}`, HOME: dir, ...extraEnv },
  });
  return { status: result.status, out: `${result.stdout}${result.stderr}` };
}

afterEach(() => {
  for (const dir of dirs.splice(0)) rmSync(dir, { recursive: true, force: true });
});

describe('railhook settings', () => {
  it('replaces a key in place, appends a new one, and leaves every other line alone', () => {
    const { dir, bin, env } = install();
    const { status } = run(dir, bin, ['settings'], 'BILLING_ENABLED=true\nCAPTCHA_SITE_KEY=0x4AAAAAAAsite\n');

    expect(status).toBe(0);
    expect(readFileSync(env, 'utf8')).toBe(
      SAMPLE_ENV.replace('BILLING_ENABLED=false', 'BILLING_ENABLED=true') + 'CAPTCHA_SITE_KEY=0x4AAAAAAAsite\n',
    );
  });

  it('keeps .env readable by its owner only', () => {
    const { dir, bin, env } = install();
    run(dir, bin, ['settings'], 'SMTP_HOST=smtp.resend.com\n');

    expect(statSync(env).mode & 0o777).toBe(0o600);
  });

  it('writes a value exactly, whatever characters it carries', () => {
    const { dir, bin, env } = install();
    const value = 'a|b&c/d$HOME e=f "g" \'h\' \\i';
    const { status } = run(dir, bin, ['settings'], `SMTP_PASSWORD=${value}\n`);

    expect(status).toBe(0);
    expect(readFileSync(env, 'utf8')).toContain(`\nSMTP_PASSWORD=${value}\n`);
  });

  it('skips blank lines and comments, and tolerates CRLF', () => {
    const { dir, bin, env } = install();
    const { status } = run(dir, bin, ['settings'], '# from GitHub\r\n\r\nEMAIL_ENABLED=true\r\n');

    expect(status).toBe(0);
    expect(readFileSync(env, 'utf8')).toContain('\nEMAIL_ENABLED=true\n');
  });

  it.each(['WEBHOOK_ENCRYPTION_KEY', 'JWT_SECRET', 'API_IMAGE_TAG'])(
    'refuses %s and writes nothing at all',
    (key) => {
      const { dir, bin, env } = install();
      const { status, out } = run(dir, bin, ['settings'], `BILLING_ENABLED=true\n${key}=rotated-by-a-deploy\n`);

      expect(status).not.toBe(0);
      expect(out).toContain(key);
      expect(readFileSync(env, 'utf8')).toBe(SAMPLE_ENV);
      expect(readdirSync(dir).filter((f) => f.startsWith('.env.'))).toEqual([]);
    },
  );

  it('refuses a line that is not a variable name', () => {
    const { dir, bin, env } = install();
    for (const input of ['billing_enabled=true\n', '1ABC=x\n', 'NOT A LINE\n', 'BAD-NAME=x\n']) {
      const { status } = run(dir, bin, ['settings'], input);
      expect(status, input).not.toBe(0);
      expect(readFileSync(env, 'utf8'), input).toBe(SAMPLE_ENV);
    }
  });

  it('names what changed and never prints a value', () => {
    const { dir, bin } = install();
    const secret = 're_supersecretresendkey123';
    const ok = run(dir, bin, ['settings'], `SMTP_PASSWORD=${secret}\nSMTP_HOST=localhost\n`);
    expect(ok.status).toBe(0);
    expect(ok.out).toContain('SMTP_PASSWORD');
    expect(ok.out).not.toContain(secret);

    const refused = run(dir, bin, ['settings'], `SMTP_PASSWORD=${secret}\nJWT_SECRET=${secret}\nlower=${secret}\n`);
    expect(refused.status).not.toBe(0);
    expect(refused.out).not.toContain(secret);
  });
});

describe('railhook upgrade reads the settings a deploy sends', () => {
  it('stops before the backup, having changed nothing, when a setting is refused', () => {
    const { dir, bin, env } = install();
    // Skips the helper refresh, which would fetch install.sh from GitHub.
    const { status, out } = run(dir, bin, ['upgrade', 'v2.17.2'], 'JWT_SECRET=x\n', { RAILHOOK_HELPER_REFRESHED: '1' });

    expect(status).not.toBe(0);
    expect(out).not.toMatch(/Backing up/);
    expect(readFileSync(env, 'utf8')).toBe(SAMPLE_ENV);
  });

  it('applies them before it pins the images or takes the backup', () => {
    const helper = helperSource();
    const upgrade = helper.slice(helper.indexOf('    upgrade)'));
    const applied = upgrade.search(/\[ ! -t 0 \][^\n]*\n?[^\n]*apply_settings/);
    expect(applied, 'upgrade applies stdin settings when stdin is not a terminal').toBeGreaterThan(-1);
    expect(applied).toBeGreaterThan(upgrade.indexOf('exec "$0" upgrade'));
    expect(applied).toBeLessThan(upgrade.indexOf('Pinned API/WORKER/UI image tags'));
    expect(applied).toBeLessThan(upgrade.indexOf('Backing up before anything changes'));
  });
});

describe('the deploy workflow sends them', () => {
  const workflow = read('.github/workflows/deploy-prod.yml');

  it('builds the payload from DOTENV_-prefixed variables and a named list of secrets', () => {
    expect(workflow).toMatch(/toJSON\(vars\)/);
    expect(workflow).toContain('DOTENV_');
    expect(workflow).not.toMatch(/toJSON\(secrets\)/);
    expect(workflow).toMatch(/DOTENV_SMTP_PASSWORD: \$\{\{ secrets\.DOTENV_SMTP_PASSWORD \}\}/);
  });

  it('pipes it into the forced deploy command', () => {
    const deploy = workflow.slice(workflow.indexOf('- name: Deploy\n'));
    expect(deploy).toMatch(/"deploy \$\{VERSION\}"\s*<\s*"\$\{?[A-Z_]+\}?"/);
  });
});
